switch: !include switch.yaml
group: !include group.yaml
automation old: !include automation_old.yaml
automation: !include automations.yaml
sensor: !include sensors.yaml
alexa: !include alexa.yaml
intent_script: !include intent_script.yaml

zwave:
  usb_path: /dev/ttyUSB0
  network_key: "0xEA, 0xAC, 0x97, 0x52, 0xE6, 0xA1, 0x2C, 0xB4, 0x01, 0x10, 0x94, 0x10, 0x65, 0x52, 0xEB, 0x63"
#  device_config:
#    light.basement1_level:
#      polling_intensity: 1
#      refresh_value: true
#      delay: 2
#    light.media_level:
#      polling_intensity: 1
#      refresh_value: true
#      delay: 2
#zha_new:
#    usb_path: /dev/ttyUSB1
#    database_path: /config/zha_new_zigbee.db
zha:
  usb_path: /dev/ttyUSB1
  database_path: /config/zigbee.db
###test
#pilight:
#  host: 192.168.1.31
#  port: 5000
#  whitelist:
#    protocol:
#      - clarus_switch
#    id:
#      - A3
#      - B3
#      - C7
#      - D11
#      - E3
#hdmi_cec:
#  devices:
#    TV: 0.0.0.0

panel_iframe:
  deluge:
    title: 'deluge'
    icon: mdi:console
    url: 'http://192.168.1.4:8112'
  portainer:
    title: 'portainer'
    icon: mdi:console
    url: 'http://192.168.1.4:9000/#/containers/'
############################################################################
homeassistant:
  name: Home
  latitude: 42.216258
  longitude: -71.42621
  elevation: 59.537
  unit_system: imperial
  time_zone: America/New_York
  customize:
    light.philips_lwb006_1046e6e7_11:
      emulated_hue_hidden: false
      friendly_name: living1
    light.philips_lwb014_022876e7_11:
      emulated_hue_hidden: false
      friendly_name: living2
    light.philips_lwb014_022a7b66_11:
      emulated_hue_hidden: false
      friendly_name: kitchen1
    light.philips_lwb014_026d9956_11:
      emulated_hue_hidden: false
      friendly_name: kitchen2
    light.philips_lwb014_027d8175_11:
      emulated_hue_hidden: false
      friendly_name: kitchen3
    light.ge_appliances_zll_light_0010e36f_1:
      friendly_name: hall
    light.media_level:
      emulated_hue_hidden: false
      friendly_name: media
    light.basement1_level:
      emulated_hue_hidden: false
      friendly_name: basement1
    switch.fan:
      emulated_hue_hidden: false
    switch.mute:
      emulated_hue_hidden: false
    group.outside:
      emulated_hue_hidden: false
    switch.entry:
      emulated_hue_hidden: false
    switch.tv:
      emulated_hue_hidden: false
    switch.four:
      emulated_hue_hidden: false
    switch.five:
      emulated_hue_hidden: false
    switch.twenty_five:
      emulated_hue_hidden: false
    switch.sixty:
      emulated_hue_hidden: false
    switch.single_monitor:
      emulated_hue_hidden: false
    switch.computer_force_idle:
      emulated_hue_hidden: false
    switch.computer:
      emulated_hue_hidden: false
    light.cree_connected_a19_60w_equivalent_fe024a16_10:
      friendly_name: b_stairs
    group.downstairs:
      order: 1
    group.upstairs:
      order: 2
#############################################################################
zone:
  name: Home
  latitude: 42.216258
  longitude: -71.42621
  radius: 1000
config:
frontend:
updater:
discovery:
conversation:
history:
logbook:
  exclude:
    entities:
      - sensor.computer_status
      - light.kitchen1
      - light.kitchen2
      - light.kitchen3
      - sensor.office_motion
sun:
notify:
  - name: pushbullet
    platform: pushbullet
    api_key: !secret pushbullet_api
##################### emulated_hue #################################################
emulated_hue:
  host_ip: 192.168.1.4
  expose_by_default: false
#####################media player#################################################	
media_player:
  - platform: plex
    scan_interval: 1
    show_all_controls: false
    use_custom_entity_ids: false
    use_episode_art: true
    include_non_clients: true
########################### mqtt broker ###########################################
mqtt:
  broker: 192.168.1.4
####################### HTTPS ###############################################
http:
  api_password: !secret api_password
#  ssl_certificate: !secret ssl_cert 
#  ssl_key: !secret ssl_key 
#  base_url: !secret base_url
#  trusted_networks:
#    - 127.0.0.1
#    - ::1
#    - 192.168.1.0/24
#    - 2001:DB8:ABCD::/48
  login_attempts_threshold: 5
########## Tracker ###########################################################
device_tracker:
  - platform: bluetooth_tracker
    track_new_devices: false
  - platform: asuswrt
    host: 192.168.1.1
    username: admin
    password: !secret router_password
  - platform: nmap_tracker
    hosts: 
      - 192.168.1.80
      - 192.168.1.77
    
#camera:
#  - platform: mjpeg
#    mjpeg_url: http://192.168.1.79:8081/video.mjpg?q=30&fps=33&id=0.34812694693314183&r=1499382657451
########### Hue ###########################################################
light:
  - platform: yeelight
    devices:
      192.168.1.202:
        name: yeelight1
#        transition: 1000
#        use_music_mode: True 
      192.168.1.246:
        name: yeelight2
#        transition: 1000
#        use_music_mode: True 
########### thermostats #####################
##################### keyboard ##################################################
keyboard_remote:
  device_descriptor: '/dev/input/by-id/usb-flirc.tv_flirc-event-kbd'
  type: 'key_down'
###################### sensor #########################################################
################ Shell ######################################################
shell_command:
  open_vpn_on: '/config/Scripts/open_vpn_on.sh'
  open_vpn_off: '/config/Scripts/open_vpn_off.sh'
  restart_router: '/config/Scripts/reboot_router.sh'
  hibernate: 'wget http://192.168.1.79/?message=hibernate'
  turn_off_basement_tv: "curl -d '' http://192.168.1.118:8060/keypress/PowerOff"
  channel_4: "/config/Scripts/changeChannel.sh 4.1"
  channel_60: "/config/Scripts/changeChannel.sh 60.5"
  channel_5: "/config/Scripts/changeChannel.sh 5.1"
  channel_7: "/config/Scripts/changeChannel.sh 7.1"
  channel_25: "/config/Scripts/changeChannel.sh 25"
  mute: "curl -d '' http://192.168.1.82:8060/keypress/VolumeMute & curl -d '' http://192.168.1.118:8060/keypress/VolumeMute &"
  pause: "curl -d '' http://192.168.1.82:8060/keypress/Play & curl -d '' http://192.168.1.118:8060/keypress/Play &"
  play: "curl -d '' http://192.168.1.82:8060/keypress/Play & curl -d '' http://192.168.1.118:8060/keypress/Play &"
  power: "curl -d '' http://192.168.1.82:8060/keypress/Power"
  volume_up: "curl -d '' http://192.168.1.82:8060/keypress/VolumeUp & curl -d '' http://192.168.1.118:8060/keypress/VolumeUp &"
  volume_down: "curl -d '' http://192.168.1.82:8060/keypress/VolumeDown & curl -d '' http://192.168.1.118:8060/keypress/VolumeDown &"
  restart_hass: 'curl http://127.0.0.1:8126/container/hass/restart'
###################### Input Selectors #################################
input_select:
  current_game:
    name: current_game
    options:
     - PC
     - PS4
###################### Scripts #############################################
script:
  restart_hass:
    alias: Restart Home Assistant
    sequence:
      - service: shell_command.restart_hass
  steam_script:
    sequence:
      - service: remote.send_command
        data:
          entity_id: remote.harmony_hub
          device: 50117060
          command:
            - ok
      - delay: 00:00:20
      - service: remote.send_command
        data:
          entity_id: remote.harmony_hub
          device: 50117060
          command:
            - ok
            - ok
          delay_secs: 1
  pc_on_tv:
    sequence:
      - service: remote.send_command
        data:
          entity_id: remote.harmony_hub
          device: 48790222
          command:
            - PowerOn
      - delay: 00:00:20
      - service: remote.send_command
        data:
          entity_id: remote.harmony_hub
          device: 48790222
          command:
            - InputHdmi4
      - service: remote.send_command
        data:
          entity_id: remote.harmony_hub
          device: 48790222
          command:
            - Mute
      - service: switch.turn_on
        data:
          entity_id: switch.computer
      - service: switch.turn_off
        data:
          entity_id: switch.single_monitor
  pc_off_tv:
    sequence:
      - service: remote.send_command
        data:
          entity_id: remote.harmony_hub
          device: 48790222
          command:
            - PowerOff
      - service: switch.turn_on
        data:
          entity_id: switch.single_monitor
      - delay: 00:00:20
      - service: switch.turn_off
        data:
          entity_id: switch.computer
  ps4_on_tv:
    sequence:
      - service: remote.send_command
        data:
          entity_id: remote.harmony_hub
          device: 48790222
          command:
            - PowerOn
      - delay: 00:00:20
      - service: remote.send_command
        data:
          entity_id: remote.harmony_hub
          device: 48790222
          command:
            - Mute
      - service: remote.send_command
        data:
          entity_id: remote.harmony_hub
          device: 48790222
          command:
            - InputHdmi5
  ps4_off_tv:
    sequence:
      - service: remote.send_command
        data:
          entity_id: remote.harmony_hub
          device: 48790222
          command:
            - PowerOff
  four:
    sequence:
      service: shell_command.channel_4
  five:
    sequence:
      service: shell_command.channel_5
  seven:
    sequence:
      service: shell_command.channel_7
  twenty_five:
    sequence:
      service: shell_command.channel_25
  sixty:
    sequence:
      service: shell_command.channel_60
  play:
    sequence:
      service: shell_command.play
  power:
    sequence:
      service: shell_command.power
  bedtime:
    sequence:
      - delay:
          minutes: 2
      - service: homeassistant.turn_off
        entity_id: group.downstairs
  bedroom_off:
    sequence:
      - service: switch.turn_off
        entity_id: switch.bedroom_all
      - service: switch.turn_off
        entity_id: switch.bedroom_all
      - service: switch.turn_off
        entity_id: switch.bedroom_all
  bedroom_on:
    sequence:
      - service: switch.turn_on
        entity_id: switch.bedroom_all
      - service: switch.turn_on
        entity_id: switch.bedroom_all
      - service: switch.turn_on
        entity_id: switch.bedroom_all
  3times_entry:
    sequence:
      - service: switch.turn_on
        entity_id: switch.entry
      - service: switch.turn_on
        entity_id: switch.entry
      - service: switch.turn_on
        entity_id: switch.entry
  set_the_mood:
    sequence:
      - service: light.turn_on
        data:
          entity_id: light.office
          brightness_pct: 25
      - service: light.turn_off
        data:
          entity_id: light.media
  normal:
    sequence:
      - service: light.turn_on
        data:
          entity_id: light.office
          brightness_pct: 100
      - service: light.turn_on
        data:
          entity_id: light.media
          brightness_pct: 100
  volume_up:
    sequence:
      - service: shell_command.volume_up
      - service: shell_command.volume_up
      - service: shell_command.volume_up
      - service: shell_command.volume_up
      - service: shell_command.volume_up
  volume_down:
    sequence:
      - service: shell_command.volume_down
      - service: shell_command.volume_down
      - service: shell_command.volume_down
      - service: shell_command.volume_down
      - service: shell_command.volume_down
  mute:
    sequence:
      service: shell_command.mute
#  fox:
#    sequence:
#      service: shell_command.channel_25
