- platform: mqtt
  name: "esp_motion"
  state_topic: "/esp/motion"
- platform: mqtt
  name: "b_temp"
  state_topic: "smartthings/Xiaomi/temperature"
  unit_of_measurement: '°F'
- platform: mqtt
  name: "b_humidity"
  state_topic: "smartthings/Xiaomi/humidity"
  unit_of_measurement: '%'
- platform: mqtt
  name: "computer_status"
  state_topic: "computer/status"
- platform: mqtt
  name: "aeon_minimote"
  state_topic: "smartthings/Aeon Minimote/button"
################## batteries ########################
##########################################################
- platform: broadlink
  host: 192.168.1.52
  mac: B4:43:0D:EE:F6:1C
  monitored_conditions:
    - 'temperature'
- platform: template
  sensors:
    downstairs_temp:
      value_template: '{{(states("sensor.broadlink_sensor_temperature")|float * 0.95)|round(1)}}'
      friendly_name: 'downstairs_temp'
      unit_of_measurement: '°F'
#- platform: plex
#  host: 192.168.1.4
#  username: derocheam
#  password: hockey
- platform: yweather
  forecast: 1
  name: yw_day1
  monitored_conditions:
    - weather
    - temp_min
    - temp_max
- platform: yweather
  monitored_conditions:
    - weather
    - weather_current
    - temp_min
    - temp_max
    - temperature
- platform: template
  sensors:
    alarm_state:
      value_template: >-
        {% if 'disarmed' in states('sensor.ifttt_email') %} disarmed
        {% elif 'armed away' in states('sensor.ifttt_email') %} away
        {% elif 'armed night' in states('sensor.ifttt_email') %} night
        {% elif 'armed stay' in states('sensor.ifttt_email') %} stay
        {% endif %}
#- platform: command_line
#  command: curl  http://192.168.1.82:8060/query/device-info | grep PowerOn | wc -l
#  scan_interval: 5
#  name: living_tv